### ISSUE TITLE
Setup publishing release .jars to GitHub packages

### ISSUE THREAD

**Issue by dougb** [target/data-validator#2]
Setup publishing release .jars to maven central or some other jar hosting place.

**Comment by dougb** [comment]
Looking into the requirements to PGP sign artifacts from [here](https://maven.apache.org/repository/guide-central-repository-upload.html). I think this means that we can't have CI publish artifacts automatically.

**Comment by colindean** [comment]
We should be able to set the private key for CI somehow.

**Comment by colindean** [comment]
Unless we want to heed the warning: 

> Warning: Do not store production secrets in the API during the limited public beta period. Production workflows should not be used during the limited public beta.

**Comment by colindean** [comment]
Literally today: https://github.blog/2019-05-10-introducing-github-package-registry/

https://help.github.com/en/articles/about-github-package-registry
https://help.github.com/en/articles/configuring-maven-for-use-with-github-package-registry

**Comment by colindean** [comment]
We'll need someone with org admin perms to add the app to the org: https://github.com/features/package-registry/signup

**Comment by colindean** [comment]
How-to for publishing to Github Packages: https://gist.github.com/djspiewak/2359e5d742cd0d7161cf3422e36fcaf3
