### ISSUE TITLE
Test fails for ConfigVarSpec

### ISSUE THREAD

**Issue by JyotiRSharma** [target/data-validator#66]
When running sbt clean assembly on terminal, the following tests are failing:

```
[info]   - from Json snippet
[info]   - addEntry works *** FAILED ***
[info]     sut.addEntry(ConfigVarSpec.this.spark, varSub) was true (ConfigVarSpec.scala:70)
[info]   - asJson works
[info]   - var sub in env value *** FAILED ***
[info]     sut.addEntry(ConfigVarSpec.this.spark, varSub) was true (ConfigVarSpec.scala:83)
[info]   - var sub fails when value doesn't exist
```
Here is the ScalaTest output:
```
[info] ScalaTest
[info] Run completed in 3 minutes, 2 seconds.
[info] Total number of tests run: 330
[info] Suites: completed 25, aborted 0
[info] Tests: succeeded 328, failed 2, canceled 0, ignored 0, pending 0
[info] *** 2 TESTS FAILED ***
[error] Failed: Total 330, Failed 2, Errors 0, Passed 328
[error] Failed tests:
[error]         com.target.data_validator.validator.ConfigVarSpec
[error] (Test / test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 892 s (14:52), completed 10 Jan, 2022 8:36:27 AM
```

**Comment by colindean** [comment]
Is this on a fresh clone?

**Comment by colindean** [comment]
Please provide some details about your environment, e.g. OS and its version, output of `java -version`, etc. Check the commands I added in https://github.com/target/data-validator/pull/67 for what I'm most interested in...

**Comment by colindean** [comment]
Your SBT version output is strange. It's missing the right version information. SBT should be 1.5.7 and should have the version of DV set from the git tag. Are you using a git clone or a source dump?

I tried reproducing your setup with Docker:

```bash
docker run --rm -it -v "`pwd`:/dv" ubuntu:18.04 bash
```

in container:

```bash
apt update && apt install openjdk-8-jdk-headless curl
java -version
cd /dv
bin/sbt version
bin/sbt test
```
```
openjdk version "1.8.0_312"
OpenJDK Runtime Environment (build 1.8.0_312-8u312-b07-0ubuntu1~18.04-b07)
OpenJDK 64-Bit Server VM (build 25.312-b07, mixed mode)
[info] welcome to sbt 1.5.7 (Private Build Java 1.8.0_312)
[info] loading settings for project dv-build from assembly.sbt,plugins.sbt ...
[info] loading project definition from /dv/project
[info] loading settings for project dv from build.sbt ...
[info] set current project to data-validator (in build file:/dv/)
[info] 0.13.0-3-gc17ec6a
```

… but I'm able to reproduce the test failure in the container. Strange. I'll continue to look into it. 

I suspect a JDK difference, but not ready to throw up my hands on it yet. On the primary computer I use for DV development, I'm using Temurin 1.8.0_302 (installed with Homebrew) and on another, I think I'm on [OpenJDK 8 8u312-b07-0ubuntu1~20.04](https://packages.ubuntu.com/focal/openjdk-8-jdk-headless) and it's a fresh installation of the OS as of yesterday.

**Comment by colindean** [comment]
On a whim, I tried against OpenJDK 11 in the container and those two tests failed for the same reason (as did many other tests).

I'm working on getting logs to show so I can see what's happening inside of `NameEnv#addEntry`: I speculate that it's hitting the inaccessible or error branch and the interface of that method is painful since `true` means it failed. I might refactor it for good measure…

**Comment by colindean** [comment]
I think I figured it out.

```
22/01/11 03:23:57 ERROR NameEnv: Variable 'java_home' cannot be processed env variable 'JAVA_HOME' not found!
[info]   - addEntry works *** FAILED ***
[info]     sut.addEntry(ConfigVarSpec.this.spark, varSub) was true (ConfigVarSpec.scala:70)
…
22/01/11 03:23:57 DEBUG VarSubstitution$: getVarName(K: ${h}) ret: Some(h)
22/01/11 03:23:57 DEBUG VarSubstitution: foundVar: (${h},Some("HOME"))
22/01/11 03:23:57 DEBUG VarSubstitution: accum: JAVA_${h} variable: ${h} json: Some("HOME")
22/01/11 03:23:57 DEBUG VarSubstitution$: src: JAVA_${h} oldVal: ${h} newVal: HOME ret: JAVA_HOME
22/01/11 03:23:57 DEBUG VarSubstitution: Replaced 'JAVA_${h}' with 'JAVA_HOME'
22/01/11 03:23:57 INFO NameEnv: Substituting java_home var: JAVA_${h} with `JAVA_HOME`
22/01/11 03:23:57 ERROR NameEnv: Variable 'java_home' cannot be processed env variable 'JAVA_HOME' not found!
22/01/11 03:23:57 DEBUG VarSubstitution$: getVarName(K: ${h}) ret: Some(h)
22/01/11 03:23:57 DEBUG VarSubstitution: missingVar: (${h},None)
22/01/11 03:23:57 DEBUG VarSubstitution: errs: ${h}
22/01/11 03:23:57 DEBUG VarSubstitution$: getVarName(K: ${h}) ret: Some(h)
[info]   - var sub in env value *** FAILED ***
22/01/11 03:23:57 WARN NameEnv: Field: java_home msg: ValidatorError(VariableSubstitution: Can't find values for the following keys, h)
22/01/11 03:23:57 ERROR NameEnv: Variable 'java_home' cannot be processed env variable 'JAVA_${h}' not found!
[info]     sut.addEntry(ConfigVarSpec.this.spark, varSub) was true (ConfigVarSpec.scala:83)
```

These are failing because the `JAVA_HOME` variable isn't set in the container! `JAVA_HOME` is much more meaningful on macOS, which is the OS on which DV was developed primarily but it's been tested on Linux in CI, where invariably `JAVA_HOME` must be getting set.

If I set `JAVA_HOME`:

```bash
export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64
bin/sbt test
```
then it passes.

I'm working on a patch that will insert `JAVA_HOME` into the test runner environment if it's missing.

**Comment by JyotiRSharma** [comment]
Yes JAVA_HOME was an underlying issue here..
Thanks a million.. :)
